# This is a basic workflow to help you get started with Actions

name: CI
env:
  pull_code: "PowerShell_Scripts"
  push_to: "PS-Script-${{ github.sha }}"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, WKD!
      - name: List Folders
        run: ls -la

      - name: Run a multi-line script
        run: |
          echo Somebody pushed
          echo "Commit of new Push is: ${{ env.push_to }}"
