# This is a basic workflow to help you get started with Actions

name: CI
env:
  pull_code: "PowerShell_Scripts"
  push_to: "PS-Script-${{ github.sha }}"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VAR1: "This is Job Level Variable1"
      VAR2: "This is job Level Variable2"
      
    steps:
      - name: Run a one-line script
        run: echo Hello, WKD!
      - name: Print env vars
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is Super local Environment variable"
        
      - name: Full clone my repository
        uses: actions/checkout@v1
      - name: List Folder
        run: ls -la

      - name: Run a multi-line script
        run: |
          echo Somebody pushed
          echo "Commit of new Push is: ${{ env.push_to }}"
          
      - name: Lets test some packages if they are here 1
        run: aws --version
       
      - name: Lets test some packages if they are here 2
        run: zip --version
